sudo: false

language: python
cache: pip

matrix:
  include:
    - python: '3.5'
      env:
        - FLASK_APP=autoapp.py FLASK_DEBUG=True APP_SETTINGS=cloudlabs.config.DevConfig
    - python: '3.6'
      env:
        - FLASK_APP=autoapp.py FLASK_DEBUG=True APP_SETTINGS=cloudlabs.config.DevConfig
    - python: '3.6'
      env: PEP8=1

services:
  - postgresql

install:
  - pip install -r requirements/local.txt
  - |
    # Check if this is the PEP8 test instance and install pycodestyle
    if ! [ -z "$PEP8" ]; then
       pip install pycodestyle
    fi

script:
  - |
    # Check if this is the PEP8 test instance and run pep8
    if [ -z "$PEP8" ]; then
      cd src
      PYTHONPATH=. py.test -s
    else
      pycodestyle ./
    fi

env:
  global:
    # TF_VAR_azure_client_id
    - secure: "OMhRAh3xM3N+Cqkjh9GKVjy1boY+FWgs0LfBZmCFIkyZbU4htosKETwHP84I85zk7DFugumoxWS2Qq4B1cMQ6V0u30BHS9oZBob+4kHGxEVoWN7R5mKxsNFL0NxtET08EgViuxt+wMuf08hKu5h8hWjHhZPMs8mzt+su2UHGQDocFcpuVh7OTFImvlS2q7EX/2zmahOfb0Vr+OsGuKhmCTA8UEcX5Z9MVLuIUgtZCRZU0hDTbVHmjeNk9iMc/e/3XKrxvx/acLUAr1pekzERL853uupyMcCha4yk8UgyhyQfeMiFzWUZ/Prxb3zM2cO2dz+RK25A8sQECO7LH56bZbvzCs81M1XI0bP8rvOblEw4EZglIaEud7b/AXMhw6wUdKG+HGQnAkckuP0oCWtvUoxKo02sKmv4eF06L8QOBV+0e5yo0Vpqb6uxhojIbnzIwjWnfDtrVp7TQPP8z1dTjwajBGQHFaUEnFWBy/A9Je/w3PhfeIOuzE5kvP2pnor6Wppk5CEVyOkRZzN5Z7NFqL6mRZKYjsSV9ZViZn9MUg/8PJ5GS79KOgoWUYrb4aT3JgWws5Npo75aJ0EaLjvZLBbOlBHLjnDk8nHvtCnP61Va6Hrnbyd8DJPP92UXn1p6V1DH8/7D7dZuTXeB9YIharJuDdWAdBwfYSBhMpc0zfA="
    # TF_VAR_azure_tenant_id
    - secure: "jO+qrvtZFeM8/rWcmoVaIQuijYgIgzs6g06gh2jp0cIQwxVGJpY6zIZjFv6WJFR/GV2r6oxHaPrfb9VfGQhZ4IzsVEhMYv04aYiyE5rFV/PEn+vJn7P1aTi2m208r056iXhMVADa1HARMawOOTXImnJ4DSEMomzilPIkMTjYiJ67ijwdBk7pv+fb1r4Xm2NEavC8G9u7moHukMlXNqBqQNbCGMUL7bSAehD/fIGYzYkqB0ByKtpVAQGNkB1SmXKKxaPnpWMAlRToA9S7GJQEkOngul2jpKCeg/HhXMhGwO62zWSBRdJM+rK0mBLDBY9VUuPxRISlQq9U757eGTJCH9HbW2+Kr+mE+8iylxiYV4RbCCy8Lby2ibdv7uTQLSeVJyG25Zm04mQtv0w6y7Gi+jJQXMgM9leyi+ChWCQQ6KpHmyvJF6408SNoou/fui06QosWcM75sg4SMGfIxvjN0gP9m19S8leblIx0MW8QwxPaTNTVrNv1IHnLyMdvHxACn0w5q46pxW99//2vqhx9MfB2srEotH9zdFxZTv8QdYsMMT08miGD+Dm+EuVyb6pqXJqaXnjqcsucdKa+4BSEeDHDQKyOtCd71Zzlv7Q3FiZEaG2ECk1OGJ/jVoLp2hZCwpGpASft7gkeYQWg6aZWEjlxpqedkTJAsEvEy9tuxWQ="
    # TF_VAR_azure_client_secret
    - secure: "VPAUnx12PVJ9uaAkt0+U3JdcrK3ZKJtBB2J2yYV6AjtPpd510p7IhC8Fi4qhGpv35m7oYstmK7CQ1cmMbxCdyV1L6B0713twHnGh2dlv/EdZVhLckVHlkocAAgmKWlA8ZtAaQey6l37lpMkpg2XxFL9C0BwtNbZiWiuR4Ojk+u1p0me02pryJfQN787Jf1cLdGljhh8li9zWiR7ITJJ203MC4qs/VQOAzngDqQoi6WH0d/cehID2UKkh+jM/vKf/v6u9yjQ0fpZzJFfSKpwBfMQ7NiIZ+l+J1vCx8zFp2lu8XxOqmVin5RYnbagmsL/5M4UnsmACJcjbmJAacmSXjauYktkxNQ+UrkLRu0EhE6gvIP/hVX1xXWZaitkN9y31GVnacgn2KGIeRp0W3dx8/o3sAXtdka8somi6MNin0wgotLQno0KfHtGp9xUus+n/1yMaJzqcHlqk5RLfHtyuQQcAKBCtFjcUbxFr4qM+hohF9zxjolCS1gWUtAXWvEEKFio+S2BeRLIlzYTiz8jmwNa9qTMLwJr6yfVO8HyuuiWzvLgaR6EI0mSlWg+V3m/2PsDxEKsCGcuNznx6Ir5Top966+Isj2/uV1/WNUDjrZeufzPc/AgA3PzJHUnvdfaFhws0oE4UygUc/m393bbLhBsfmEXdMW1hWRXUzjvjmDU="
    # TF_VAR_azure_subscription_id
    - secure: "MoObsSQGXg52GBRC50JEOjH5f/0IorisqfXWarnZksiBnnqUlsyuaMciB++VDsOFa3BjaN1EzRiCixYKxubCzdfjsLkwFEYWsxI75/+3jvrdqhjKM693NguzaIz8GvDukx6WKmkIxa4E2N5VABIk08V9Ltbh7OB1CDucsgOS22Mx3lwcoVxOvJLj3AnxwqrnGGBfprgXxa7zMH1qxYb/pLTN6j3VsfADsWoeQfcKO7+sw1HnBtHsVjs0DzWTyKsKPJNxXbmSKf2BtOp1mxr2gQ7LF9Rw996aD4HSl4vyMup7Cl0Jz1cQetnknwK+er9njgc0vaG7S9v7ZfB9xnhDs8wUbZ8y4N7lVJK7KnhlbkQVpZIsP6gPjVGJxff6HgxqK4U0wprcJratRA5gyD4Ni9lzt3JG1IGco72SCElsA0+LiU5oW5u1gWT8CetM0AtkeFnntS7HznPJQmvtEvoe2b15Z0l215TQgHADyXNvg9CVdhk6hM05zs3x5+dzl4gQoN8Ul/VbTzsABGnJ03ji/k8DhFgalC6/QX7jdyuU27+uKVt6cV3vEDyy4GVGCvFwqnsuellGtw4FupkbeE33SrsbHieMcUOjhn93JnhoXsaq7yMMuq1j1jmDcNojjd92j4nGdiHIpm3q9hiQwf+ucrKerGxcu1T9K/PD6Ju9VSI="

before_install:
  - |
    # Unfortunately this is the only way at the moment to install Terraform in Ubuntu
    curl -sSL -o terraform.zip "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" ;
    mkdir terraform;
    unzip terraform.zip -d terraform/ ;
    chmod +x ./terraform/terraform ;
    export PATH=$PWD/terraform:$PATH ;
    terraform version ;
  - |
    pwd
    openssl aes-256-cbc -K $encrypted_385610be50e6_key -iv $encrypted_385610be50e6_iv -in .travis.tar.enc -out .travis.tar -d
    tar xvf .travis.tar

before_script:
  - |
    cd src
    createdb --echo cloudlabs
    flask db upgrade
    cd -
