sudo: false

language: python
cache: pip

matrix:
  include:
    - python: '3.4'
      env:
        - FLASK_APP=autoapp.py FLASK_DEBUG=True APP_SETTINGS=cloudlabs.config.DevConfig
    - python: '3.6'
      env:
        - FLASK_APP=autoapp.py FLASK_DEBUG=True APP_SETTINGS=cloudlabs.config.DevConfig
    - python: '3.6'
      env: PEP8=1

services:
  - postgresql

install:
  - pip install -r requirements/local.txt
  - |
    # Check if this is the PEP8 test instance and install pycodestyle
    if ! [ -z "$PEP8" ]; then
       pip install pycodestyle
    fi

script:
  - |
    # Check if this is the PEP8 test instance and run pep8
    if [ -z "$PEP8" ]; then
      cd src
      PYTHONPATH=. py.test -s
    else
      pycodestyle ./
    fi

env:
  global:
    # TF_VAR_azure_client_id
    - secure: "B2vOMsjgrhdXtKfNOKP1EIj2IL/19qiebbXj9fTqAdZemyeKc8s0BpqDK8w/fug+5n+cdf+/nGJ1ZndGxyP60jxSEzGcssBbzUWCCRi6/GgvOJpK10aqTuv+ZXGMJs9L8VUA1W1H1KbTcRtZvGZh1q2+eWQ7ZG8Gq4t4s1KSdgh0TwP9Mm8Fmp8nfcuJnxAwu+mmWhv+PynIJLp1YtrvlvqdLnB1CmSb5KHeuvV5mf7wB384vfi1+I5DAcGUEn76dSfhbpgIMggCg3MzNxm/UFq5eiWguZ94FduUKm5xuHQOqHP2/D7Fn+MRP78KpoY4F8YnfC7DL6N5c5wsLrHOCbe+bDy+p3bFE6cZ9EQjPz9n/DOLrPkSSQkctnD9FkNuu0OTabtGKX0Ljd/R38zlYPTSgBLiJfVfdrM6IKQY2he4kC+1ArPfKWtQGUzz+w03oEM0Dmn2LqFy6oNXjhvOCKTJZQIaDtrMSIu8VU+owXSpP+lCeM9VRsWK67Yuf4iE1XUCHpFEvGQN3Cd9t7dBFVh4fa9AQa7lHzw/JyHMH3ay723GMae/x3Z8gtGnfa+KjnM2fDR3VqYt2CYpecrjBVvLEryx5JyyU4lGJK13g3brWQIvcZikWzOFCZ/HMTqNdC2uCO5RHQlrob3ujHwh3vsPrLxETP0Jq7oHRFiIONE="
    # TF_VAR_azure_tenant_id
    - secure: "jO+qrvtZFeM8/rWcmoVaIQuijYgIgzs6g06gh2jp0cIQwxVGJpY6zIZjFv6WJFR/GV2r6oxHaPrfb9VfGQhZ4IzsVEhMYv04aYiyE5rFV/PEn+vJn7P1aTi2m208r056iXhMVADa1HARMawOOTXImnJ4DSEMomzilPIkMTjYiJ67ijwdBk7pv+fb1r4Xm2NEavC8G9u7moHukMlXNqBqQNbCGMUL7bSAehD/fIGYzYkqB0ByKtpVAQGNkB1SmXKKxaPnpWMAlRToA9S7GJQEkOngul2jpKCeg/HhXMhGwO62zWSBRdJM+rK0mBLDBY9VUuPxRISlQq9U757eGTJCH9HbW2+Kr+mE+8iylxiYV4RbCCy8Lby2ibdv7uTQLSeVJyG25Zm04mQtv0w6y7Gi+jJQXMgM9leyi+ChWCQQ6KpHmyvJF6408SNoou/fui06QosWcM75sg4SMGfIxvjN0gP9m19S8leblIx0MW8QwxPaTNTVrNv1IHnLyMdvHxACn0w5q46pxW99//2vqhx9MfB2srEotH9zdFxZTv8QdYsMMT08miGD+Dm+EuVyb6pqXJqaXnjqcsucdKa+4BSEeDHDQKyOtCd71Zzlv7Q3FiZEaG2ECk1OGJ/jVoLp2hZCwpGpASft7gkeYQWg6aZWEjlxpqedkTJAsEvEy9tuxWQ="
    # TF_VAR_azure_client_secret
    - secure: "GFbR+XT39SREgDqy1tpTUBxK7H9wClVe/75MneDrLIuFq1NeaFxOXfHKwNyut7ZP2hi+tMQ2bJH+ij+IdJQzl2/W//jjedaTNrone25LZM80l7oZWWBxnL9M4mb6vlASjjBjPFIF0BhemKfq+Zmc2TTHy/smpZcochHR/XTu26J/JYZWbVwvlmDKSzNgQIMaaKcAwKGZ47kEWmpostJ4f6rn7/JQXXi9iqfse8Vl1c74kVnhmNwmiE0OJydwZiI/b26nqr5pEYq1esCXkHTlg2fEuWpDVbgAqlcVNoz2bLfyPL2Tzz7k3SswB+rjjxFDZas5p72b5nxBfiglg259YVL76JEDFouaO2uHuuejKbVU2vB8LxxUuNMUJfZO/5UnKrohLh0Q5g7g3VyEknt3GQz8ZfAaT6j5jYUcNzgvKDq7IpyQmnJ5wthHdb05akfNhuFzyE3dNGyZcXsZ4KWGlAYSvEbDbRzogLotnxTmGE4SG3mZyWsywwjG3SePR7qNBltiiUGtSfQ/Lnhr6YVuYCfbb395OwLcqTzKnFFsleD69G7iM584PmUiW+3PCELWGj5yU+8rK4RSBPijzQf1mjrg2TgQQnyYgb+p6Nqh/fFTy656uTApEJiwSnSq2qnJDwC3cw0yWekPlwZVuEUhctYW0EUIifDF9sVzu44ZUBM="
    # TF_VAR_azure_subscription_id
    - secure: "c0+tOdyGeQ+euSU9KCamz5yFIo+Vuvj0k5LPdcD4Hiu6S+RFU5NR7vAaKhhBE2fvkw0Lu8jl0TKmPEhKElPQ5JUR9Ap7mnLSEcY8KF9IIKaHOM+88wh0D+3XUX3PEtWUK+c6k0seTuu/2lITst+l6lErOrHKuQVs0zeaT7oTcr5nO3efgw1ad3vW84MokXcmGHimT0j7lGleXttBw6pgYJpCdexi8whJp1bWReEujcpTRrtabXgX9nH8ubCVBl687nwRcsPULZXJk8kgVRZ224/fpH12At5USnl522TMvt7WEaM0TV/ZCYihYYJKE/SLMPNkjTT3uAtdj1YX+lE+CZBKsrsJIjQFsgEPLY8IacK3fkj4iy/jlxLHbGwdEGuRPt6bLsOuIqVMkk9NPIZUkAxtOT86y3igMBL0B6r9khogeIOfl2ZcTwDr15MlPgxkmSKB0sEoxzTvF1gLxcHvAWFyHPAFHPXeT2Xg6VcEgQEiMj/3oHCl7PPnDkhl3BxwHSiB4xIXlVo3ehyJCM5gFse5b2y/DXmyMyjRdYB65+tuQ6oNZoTSKexAo+mEn0qEhxUjOvw4tCM3dwSKxn+G7kWQ56DjIeTEB4R8XF676xh7Ks5Fl03+aG+5acX79k5PvkRuIse30E4amQLjWV2iyws28APAVSJZYTp87KXkMQI="

before_install:
  - |
    # Unfortunately this is the only way at the moment to install Terraform in Ubuntu
    curl -sSL -o terraform.zip "https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_amd64.zip" ;
    mkdir terraform;
    unzip terraform.zip -d terraform/ ;
    chmod +x ./terraform/terraform ;
    export PATH=$PWD/terraform:$PATH ;
    terraform version ;
  - |
    pwd
    openssl aes-256-cbc -K $encrypted_385610be50e6_key -iv $encrypted_385610be50e6_iv -in .travis.tar.enc -out .travis.tar -d
    tar xvf .travis.tar

before_script:
  - |
    cd src
    createdb --echo cloudlabs
    flask db upgrade
    cd -
