"""empty message

Revision ID: 0ebf5dad5713
Revises: c5889224cafc
Create Date: 2018-04-19 14:53:38.789190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebf5dad5713'
down_revision = 'c5889224cafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('os_offer', sa.String(length=50)))
    op.add_column('host', sa.Column('os_sku', sa.String(length=50)))
    op.add_column('host', sa.Column('os_version', sa.String(length=50)))
    op.add_column('host', sa.Column('vm_type', sa.String(length=50), nullable=False, server_default='Standard_A4_v2'))
    op.create_index(op.f('ix_host_os_offer'), 'host', ['os_offer'])
    op.create_index(op.f('ix_host_os_sku'), 'host', ['os_sku'])
    op.create_index(op.f('ix_host_os_version'), 'host', ['os_version'])
    op.create_index(op.f('ix_host_vm_type'), 'host', ['vm_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_vm_type'), table_name='host')
    op.drop_index(op.f('ix_host_os_version'), table_name='host')
    op.drop_index(op.f('ix_host_os_sku'), table_name='host')
    op.drop_index(op.f('ix_host_os_offer'), table_name='host')
    op.drop_column('host', 'vm_type')
    op.drop_column('host', 'os_version')
    op.drop_column('host', 'os_sku')
    op.drop_column('host', 'os_offer')
    # ### end Alembic commands ###
