"""empty message

Revision ID: 1ba7e2ff81d9
Revises: f9e2a959fc9c
Create Date: 2017-10-10 18:00:18.421989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from cloudlabs.models import Host

# revision identifiers, used by Alembic.
revision = '1ba7e2ff81d9'
down_revision = 'f9e2a959fc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Some modification is required in case there are existing hosts, or the
    # empty fields in that row will violate the non-null constraint. To address
    # this, we first allow the column to have null values, then insert a
    # reasonable value into existing rows, and only then enforce the non-null
    # constraint.
    op.add_column('host',
                  sa.Column('base_name', sa.String(length=50), nullable=True))
    op.execute("UPDATE host SET base_name=dns_name")
    op.alter_column('host', 'base_name', nullable=False)
    op.create_index(op.f('ix_host_base_name'), 'host', ['base_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_base_name'), table_name='host')
    op.drop_column('host', 'base_name')
    # ### end Alembic commands ###
