"""empty message

Revision ID: 1ba7e2ff81d9
Revises: f9e2a959fc9c
Create Date: 2017-10-10 18:00:18.421989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba7e2ff81d9'
down_revision = 'f9e2a959fc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('base_name', sa.String(length=50), nullable=False,
        server_default='')) # add default values to keep integrity (non-null)
    #op.create_index(op.f('ix_host_base_name'), 'host', ['base_name'], unique=True)
    # removing unique=True since existing rows will have the same (empty) base_name
    op.create_index(op.f('ix_host_base_name'), 'host', ['base_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_base_name'), table_name='host')
    op.drop_column('host', 'base_name')
    # ### end Alembic commands ###
