"""empty message

Revision ID: 1fb97ad680d5
Revises: 8259c0ae0b4c
Create Date: 2018-04-19 15:10:27.727776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb97ad680d5'
down_revision = '8259c0ae0b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_host_os_offer', table_name='host')
    op.drop_index('ix_host_os_sku', table_name='host')
    op.drop_index('ix_host_os_version', table_name='host')
    op.drop_index('ix_host_vm_type', table_name='host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_host_vm_type', 'host', ['vm_type'])
    op.create_index('ix_host_os_version', 'host', ['os_version'])
    op.create_index('ix_host_os_sku', 'host', ['os_sku'])
    op.create_index('ix_host_os_offer', 'host', ['os_offer'])
    # ### end Alembic commands ###
