"""empty message

Revision ID: 43cfe688870d
Revises: 4dbff5420cc9
Create Date: 2018-02-12 17:27:10.697254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cfe688870d'
down_revision = '4dbff5420cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('task', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'task')
    # ### end Alembic commands ###
