"""empty message

Revision ID: 4d93f063452e
Revises: 43cfe688870d
Create Date: 2018-01-24 13:51:48.254451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d93f063452e'
down_revision = '43cfe688870d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'template')
    # ### end Alembic commands ###
