"""empty message

Revision ID: b7b9b0baa205
Revises: 56fd140366e3
Create Date: 2017-08-17 17:01:23.504947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b9b0baa205'
down_revision = '56fd140366e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Enum('admin', 'owner', name='roles'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_name'), 'user_roles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_name'), table_name='user_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
