"""empty message

Revision ID: d33c3fdf6b4a
Revises: 76f861afbc3e
Create Date: 2017-08-24 14:07:04.971540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33c3fdf6b4a'
down_revision = '76f861afbc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('deploy_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'deploy_log')
    # ### end Alembic commands ###
