"""empty message

Revision ID: f9e2a959fc9c
Revises: d33c3fdf6b4a
Create Date: 2017-08-24 15:05:20.945435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e2a959fc9c'
down_revision = 'd33c3fdf6b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('host', 'deploy_log',
                    existing_type=sa.TEXT(),
                    server_default='',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('host', 'deploy_log',
                    existing_type=sa.TEXT(),
                    server_default=None,
                    existing_nullable=True)
    # ### end Alembic commands ###
