version: 1

disable_existing_loggers: False

formatters:

    default:

        format: "[%(name)s] %(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]"
        datefmt: "%Y-%m-%d %H:%M:%S"


handlers:

    file_handler:

        class: logging.handlers.RotatingFileHandler

        level: DEBUG

        formatter: default

        filename: cloudlabs.log

        maxBytes: 5242880 # 5MB

        backupCount: 5

        encoding: utf8



loggers:

    cloudlabs:

        level: DEBUG

        handlers: [file_handler]

        propagate: False
